spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: CallDetailsMS
        uri: lb://CallDetailsMS/
        predicates:
        - Path=/customers/{segment}/calldetails
      - id: CustomerMS
        uri: lb://CustomerMS
        predicates:
        - Path=/customers/{segment}
      - id: FriendMS
        uri: lb://FriendMS
        predicates:
        - Path=/customers/{segment}/friends
      - id: PlanMS
        uri: lb://PlanMS
        predicates:
        - Path=/plans/**
