spring:
  application:
    name: Eureka1
server:
  port: 2222 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false        
    serviceUrl:
      defaultZone: http://localhost:2222/eureka

